title : Открытый ML курс
author: Петр Ермаков (ermakovpetr)
logo: _static/img/mlcourse_ai_logo.jpg

# Short description about the book
description: >-
  Открытый курс ods.ai по машинному обучению

repository:
  url                       : https://github.com/ermakovpetr/open-ml-course
  path_to_book              : jupyter_book
  branch: main  # Which branch of the repository should be used when creating links (optional)

execute:
  execute_notebooks           : cache
  timeout: -1

# exclude some content
exclude_patterns: []

# HTML-specific settings
html:
  favicon                     : _static/img/favicon.ico
  home_page_in_navbar         : true  # Whether to include your home page in the left Navigation Bar
  use_edit_page_button        : true  # Whether to add an "edit this page" button to pages. If `true`, repository information in repository: must be filled in
  use_repository_button       : true  # Whether to add a link to your repository button
  use_issues_button           : true  # Whether to add an "open an issue" button

# Interact link settings
notebook_interface            : "notebook"

# LaTeX settings
# bibtex_bibfiles:
#    - _bibliography/references.bib
latex:
  latex_engine                : "xelatex"
  latex_documents:
    targetname: book.tex

sphinx:
  config:
    # html_extra_path: ['_static/data']
    # html_extra_path: ['_static/img']
    html_js_files:
      - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
      - https://c6.patreon.com/becomePatronButton.bundle.js
